---
title: "Colocalization script"
site: workflowr::wflow_site
author: "Julien Bryois"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  workflowr::wflow_html:
   toc: true
   toc_float: true
editor_options:
  chunk_output_type: console
---
  
```{r setup,include=FALSE}
knitr::opts_chunk$set(autodep=FALSE, cache=FALSE, cache.lazy=FALSE, dev='png' )
```

## Libraries

```{r,message=FALSE}
library(tidyverse)
library(data.table)
library(coloc)
library(parallel)
library(biomaRt)
library(seqminer)
library(stringr)
```

# Process GWAS

## AD PGC 2025

```{r,message=FALSE}
#Read AD PGC 2025 summary statistics + light processing
sumstats <- data.table::fread('main_combined_all_neff0.6_nsumstats1.txt.gz',data.table = FALSE) %>% 
  mutate(chr=paste0('chr',chromosome)) %>% 
  dplyr::rename(bp_b37=base_pair_location) %>% 
  dplyr::select(rsid,p_value,chr,bp_b37,effect_allele,other_allele,beta,se=standard_error) %>% 
  dplyr::rename(variant_id=rsid) %>% 
  filter(!is.na(p_value))

#Read AD PGC 2025 loci, defined as most extreme coordinates of SNPs in LD with index SNP (r2>0.1, EUR population 1KG) with the GWAS index SNP
#Format:
#GWAS_snp        GWAS_snp_pos    locus_name      chrom   start   end
#rs12030051      chr1:21134597   chr1:21016155_21631472  chr1    21016155        21631472
#rs34854980      chr1:31225678   chr1:31224000_31255905  chr1    31224000        31255905

loci <- read_tsv('loci_LDlinkR.r2.0.1.EUR.txt')
```

## SNP mappings

```{r,eval=TRUE}
#Load file containing SNPs with position in both hg19 and hg38
#Format:
#chr     start       end variant_id chr_hg38  pos_hg38
#chr4 116240692 116240692  rs9999998     chr4 116240692
#chr4 162949326 162949326  rs9999997     chr4 162949326

mappings <- readRDS('variant_id_SNP_mapping.rds')

#Only keep GWAS sumstats for variant that are in the master file of all SNPs with position in both hg19 and hg38
sumstats <- filter(sumstats,variant_id%in%mappings$variant_id)
```

# Add closest gene to loci

```{r,eval=TRUE,message=FALSE}
#Add location of closest gene to the "loci" variable. Code may be optimised by directly adding this information to the "loci_LDlinkR.r2.0.1.EUR.txt" file
closest <- read_tsv('closest.protein.coding.bed',col_names = FALSE) %>% 
  setNames(c('chr_snp','start_snp','end_snp','GWAS_snp','beta','chr_gene','start_gene','end_gene','gene','distance')) %>% 
  mutate(GWAS_snp_pos=paste0(chr_snp,':',start_snp)) %>% 
  dplyr::select(GWAS_snp,GWAS_snp_pos,gene,beta,distance) %>% 
  separate(gene,into=c('symbol','ensembl'),sep='_') %>% 
  add_count(GWAS_snp_pos) %>% 
  group_by(GWAS_snp_pos) %>% 
  mutate(locus_name_gene=ifelse(n==1,symbol,paste0(symbol,collapse=' - '))) %>% 
  ungroup() %>% 
  dplyr::select(GWAS_snp_pos,locus_name_gene,beta_top_GWAS=beta) %>% 
  unique() %>% arrange(-abs(beta_top_GWAS))
loci <- left_join(loci,closest,by='GWAS_snp_pos')
```

## Coloc function

### Read eQTL sumstats

```{r}
prepare_qtl <- function(mappings_locus,file_name){
  
  #Read from tabix file for fast reading
  eqtl_locus <- tabix.read.table(file_name, paste0(unique(mappings_locus$chr_hg38),':',
                                            min(mappings_locus$pos_hg38),'-',max(mappings_locus$pos_hg38)))
  
  #If SNPS are available, get the position for that SNP, remove SNPs without eQTL beta estimate and with beta estimate = 0 + light processing. Otherwise, return NULL
  #In eQTL sumstats, A2 is often the effect allele and A1 the non-effect allele. This is set up in the code below
  if(nrow(eqtl_locus)>0) {
    eqtl_locus <- eqtl_locus %>% 
      inner_join(.,mappings_locus,by='variant_id') %>% 
      filter(!is.na(fixed_beta),
             fixed_beta!=0) %>% 
      mutate(A1=ifelse(ref==Allele,alt,ref)) %>% 
      mutate(A2=ifelse(ref==Allele,ref,alt)) %>% 
      dplyr::select(gene=feature,variant_id,p_eqtl=Fixed_P,beta_eqtl=fixed_beta,se_eqtl=fixed_sd,A1,A2) %>% 
      #Counts how many SNPs are available in the sumstats for each gene. Only keep genes with at least 10 SNPs available
      add_count(gene) %>% 
      filter(n>10)
  } else{
    return(NULL)
  }
  return(eqtl_locus)
}
```

```{r}
run_coloc <- function(tissue_sumstats,sumstats_locus){
  
  #If no eQTL sumstats, return NULL
  if(is.null(tissue_sumstats)){
    return (NULL)
  }
  #If eQTL sumstats available but no row, return NULL
  if(nrow(tissue_sumstats)==0){
    return (NULL)
  }
  
  #For each gene with an eQTL overlapping the locus of interest, run coloc + MR
  out <- lapply(unique(tissue_sumstats$gene),function(x){

    #Only keep sumstats for gene selected
    tissue_sumstats_gene <- filter(tissue_sumstats,gene==x)
    
    #Get the GWAS p-value for the SNPs with eQTL sumstats
    sumstats_locus_gene <- sumstats_locus %>% inner_join(.,tissue_sumstats_gene,by='variant_id')
    
    #Remove multi-allelic SNPs
    sumstats_locus_gene <- sumstats_locus_gene %>% add_count(variant_id) %>% filter(nn==1)
    
    #If more than 0 eQTL-GWAS SNPs are available, run coloc
    if (nrow(sumstats_locus_gene)>0){
  
     coloc_res_pval <- coloc.abf(
       dataset1=list(beta=sumstats_locus_gene$beta,
                     varbeta=sumstats_locus_gene$se^2,
                     type="cc",
                     snp=sumstats_locus_gene$variant_id),
       dataset2=list(beta=sumstats_locus_gene$beta_eqtl,
                     varbeta=sumstats_locus_gene$se_eqtl^2,
                     sdY=1,
                     snp=sumstats_locus_gene$variant_id,
                     type="quant"))$summary %>% 
       as.data.frame()
       colnames(coloc_res_pval) <- x
       
    #Get direction of effect for all SNPs at the locus
    sumstats_locus_gene <- sumstats_locus_gene %>% 
      mutate(direction=case_when(
      (effect_allele==A1 & other_allele==A2)  ~ -sign(beta*beta_eqtl),
      (effect_allele==A2 & other_allele==A1)  ~ sign(beta*beta_eqtl),
    TRUE ~ 0))
   
   #Get Proportion of positive direction
   direction_prop <- sumstats_locus_gene %>% 
     summarise(prop_pos_direction=sum(direction==1)/n()) %>% 
     setNames(x) %>% 
     as.data.frame()
   rownames(direction_prop) <- 'prop_pos_direction'
   
   direction_sign <- sumstats_locus_gene %>% 
     #Take SNP with strongest evidence of an effect on gene expression
     filter(p_eqtl==min(p_eqtl)) %>% 
     #If there are ties, take SNPs with lowest GWAS association (at random for ties).
     slice_min(n=1,p_value,with_ties=FALSE) %>% 
     summarise(snp_direction=variant_id,
               direction=direction,
               beta_gwas=case_when(
                    (effect_allele==A1 & other_allele==A2)  ~ -beta,
                    (effect_allele==A2 & other_allele==A1)  ~ beta
                    ),
              beta_eqtl=beta_eqtl,
              beta_smr=case_when(
                    direction== 1  ~ abs(beta)/abs(beta_eqtl),
                    direction== -1  ~ -(abs(beta)/abs(beta_eqtl))
                 ),
              se_gwas=se,
              p_gwas=p_value,
              se_eqtl,
              p_eqtl,
              #Get beta_smr estimate + pvalue from the gwas beta value (+se) and the eQTL beta value (+se)
              z_gwas=beta/se_gwas,
              z_eqtl=beta_eqtl/se_eqtl,
              z_smr=sqrt(((z_gwas^2)*(z_eqtl^2))/((z_gwas^2)+(z_eqtl^2))),
              p_smr=pnorm(-z_smr)*2,
              se_smr=abs(beta_smr/z_smr)) %>% 
     dplyr::select(snp_direction,beta_gwas,se_gwas,p_gwas,beta_eqtl,se_eqtl,p_eqtl,beta_smr,se_smr,p_smr,direction) %>% 
     t() %>% 
     as.data.frame()
   colnames(direction_sign) <- x
   
    #Add direction of effect to coloc results
    coloc_res_pval <- rbind(coloc_res_pval,direction_sign,direction_prop)

    return(coloc_res_pval)
    }
    else{
      return (NULL)
    }
    
})
  
  out_pvalue <- out %>% 
    bind_cols() %>% 
    t() %>% 
    as.data.frame() %>% 
    rownames_to_column('gene') %>% 
    as_tibble() %>% 
    mutate(PP.H4.abf=as.numeric(PP.H4.abf)) %>% 
    arrange(-PP.H4.abf)
  
  return(out_pvalue)
}
```

```{r}
#Add metadata data for the type of colocalization analysis (if the coloc did not return a NULL value (for e.g. if there were no SNPs in common between the GWAS and the eQTL analaysis.))
#E.g. if splicing QTL, it may be wise to set the direction to 0, as directionality is tricky to interpret.
add_meta <- function(d,type_name,set_direction_to_0=FALSE,tissue_name){
  if(!is.null(d)){
    d <- d %>% mutate(type=type_name) %>% 
      mutate(tissue=tissue_name)
    if(set_direction_to_0){
      d <- d %>% mutate(direction=0)
    }
  }
  return(d)
}
```

### Run

```{r}
#Get all eqtl_files available, should all be tabixed.
eqtl_files <- list.files('data/eqtl_sumstats/',pattern='_full_assoc.tsv.gz$',full.names = TRUE)
```

```{r}
coloc_results_all <- mclapply(1:nrow(loci),function(i){
  
  #Get coordinates from the GWAS locus from the loci file
  chrom_locus <- loci$chrom[i]
  start <- loci$start[i] %>% as.numeric()
  end <- loci$end[i] %>% as.numeric()
  
  closest_gene_locus <- loci$locus_name_gene[i]
  beta_top_GWAS_locus <- loci$beta_top_GWAS[i]
  GWAS_snp_name <- loci$GWAS_snp[i]
  GWAS_snp_pos_name <- loci$GWAS_snp_pos[i]

  #Keep GWAS sumstats of SNPs in the locus
  sumstats_locus <- filter(sumstats,chr==chrom_locus) %>% 
    filter(bp_b37>=start & bp_b37<=end) %>% 
    dplyr::mutate(SNP_id_hg19=paste0(chr,':',bp_b37))

  #Get position in hg38 using the rsid from the GWAS sumstats (which are in hg19) 
  mappings_locus <- filter(mappings,variant_id%in%sumstats_locus$variant_id) %>% 
    dplyr::select(chr_hg38,pos_hg38,variant_id) %>% 
    mutate(pos_hg38=as.integer(pos_hg38))
  
  if(nrow(mappings_locus)==0){
    return(NULL)
  }

  #Running colocalization analysis
  ### eQTL
  #### Expression
  #### For each eQTL file, load all SNPs that overlap the locus of interest and run coloc
  
  pval_eqtl <- lapply(eqtl_files,function(cell_type_file){
      cell_name <- basename(cell_type_file) %>% gsub('_eqtl_full_assoc.tsv.gz','',.)
      eqtl_file <- prepare_qtl(mappings_locus,cell_type_file)
      
      eqtl_coloc_expression <- run_coloc(eqtl_file,sumstats_locus) %>% 
        add_meta(type_name='eQTL',tissue_name=cell_name)
      }) %>% bind_rows()
  
  #If coloc results are avilable, do some light reformating
  if(!is.null(pval_eqtl) & nrow(pval_eqtl)>0){
    pval_eqtl <- pval_eqtl %>% 
      mutate(locus=loci$locus_name[i],
           coloc_method='beta') %>% 
      mutate(closest_gene=closest_gene_locus,
             beta_top_GWAS=beta_top_GWAS_locus,
             GWAS_snp=GWAS_snp_name,
             GWAS_snp_pos=GWAS_snp_pos_name)
  }
  
  results <- pval_eqtl
  if(!is.null(results) & nrow(results)>0){
    results <- results %>% 
      arrange(-PP.H4.abf) %>% 
      dplyr::select(locus,closest_gene,GWAS_snp,GWAS_snp_pos,beta_top_GWAS,everything())
  } else{
    return(NULL)
  }
  
  return(results)
},mc.cores = 6,mc.preschedule = FALSE) %>% 
  bind_rows() %>% 
  arrange(-PP.H4.abf)
```

```{r}
coloc_results_all <- coloc_results_all %>% 
  dplyr::select(locus:beta_top_GWAS,ensembl=gene,nsnps:coloc_method,gene) %>% 
  mutate(ensembl = str_replace_all(ensembl, "\\.[0-9]+", ""))
```

## Add LOEUF scores

```{r,message=FALSE}
#From supplementary Data of Gnomad: https://www.nature.com/articles/s41586-020-2308-7#Sec12
loeuf <- read_tsv('supplementary_dataset_11_full_constraint_metrics.tsv') %>% 
  filter(canonical==TRUE) %>% 
  dplyr::select(gene,gene_id,transcript,oe_lof_upper,p) %>% 
  mutate(oe_lof_upper_bin = ntile(oe_lof_upper, 10)) %>% 
  dplyr::rename(ensembl=gene_id,symbol=gene) %>% 
  dplyr::select(ensembl,oe_lof_upper_bin)
```

```{r}
coloc_results_all <- left_join(coloc_results_all,loeuf,by='ensembl')
```

## Final formating and writing

```{r}
coloc_results_all <- coloc_results_all %>% 
  dplyr::select(locus:beta_top_GWAS,symbol,ensembl,nsnps:prop_pos_direction,tissue,type,coloc_method,oe_lof_upper_bin)
```

```{r}
write_tsv(coloc_results_all,paste0('output/coloc/additional/coloc.ad_pgc_2025.txt'))
```
