#finemapping
import pandas as pd
import os
import subprocess
import time

#Note, this code was written to run on a unix system, other systems require tweaking of the script

# assign directory with intputs/outputs
# inputs are:
# GenomicRiskLoci.txt as outputted by FUMA for each phenotype
# header.txt,  a file containing the sumstats headers
# input.snps.txt.gz, a tabixed sumstats file, with columns matching the headers.txt file
base = 'path/to/dir'

#read in locusfile, in our case generated by FUMA, matching the sumstats of interest
loci = pd.read_csv(f'{base}/GenomicRiskLoci.txt', sep="\t")
if len(loci) == 0:
    exit()
#give loci numeric identifier starting from 1
loci['GenomicLocus'] = range(1, len(loci) + 1)

#make output directory
if not os.path.exists(f"{base}/loci"):
    os.makedirs(f"{base}/loci")

#iterate over loci
for index, row in loci.iterrows():
    #set header, dependent on locus file used
    chromname = "chromosome"
    if 'chromosome' not in loci.columns:
        chromname = "chr"
    chrom = int(row[chromname])
    start = int(row["start"])
    end = int(row["end"])
    #define region of interest if locus is size of bp=1
    if start == end:
        start = start - 125000
        end = end + 125000
    #set locus name to region for easy identification
    locname = f'{chrom}:{start}-{end}'
    #check if locus is fine-mapped, else skip
    if os.path.exists(f"{base}/locus_{locname}.susie.finemapped"):
        continue

    # initiate locus file
    cmd = f'cat {base}/header.txt > {base}/loci/locus_{locname}.txt'
    process = subprocess.Popen([cmd], close_fds=True, shell=True)
    process.wait()

    # get snps in locus appended to file
    cmd = f"~/tools/htslib-1.17/tabix {base}/input.snps.txt.gz {chrom}:{start}-{end} >> {base}/loci/locus_{locname}.txt"
    process = subprocess.Popen([cmd], close_fds=True, shell=True)
    process.wait()
    time.sleep(2.5)

    #read file, subset SNPs by pvalue if more than 10k SNPs in region.
    df = pd.read_csv(f'{base}/loci/locus_{locname}.txt', sep='\t')
    if len(df) > 5000:
        df = df[df['p_value'] < 0.1]
        if len(df) > 10000:
            df = df[df['p_value'] < 0.05]
        if len(df) > 10000:
            df = df[df['p_value'] < 0.005]
        df.to_csv(f'{base}/loci/locus_{locname}.txt', sep='\t', index=False)
    try:
        #munge for sumstats to right format
        cmd = f'python ~/code/polyfun/munge_polyfun_sumstats.py --sumstats {base}/loci/locus_{locname}.txt --keep-hla --out {base}/loci/locus_{locname}.txt.pq'
        process = subprocess.Popen([cmd], close_fds=True, shell=True)
        process.wait()
        time.sleep(2.5)
        
        #determine max N
        N = int(max(pd.read_parquet(f'{base}/loci/locus_{locname}.txt.pq', engine='pyarrow')['N']))

        #run polyfun wrapper of single causal variant susie impementation
        cmd = f'python ~/code/polyfun/finemapper.py --sumstats {base}/loci/locus_{locname}.txt.pq --method susie --out {base}/loci/locus_{locname}.susie --n {N} --max-num-causal 1 --chr {chrom} --start {start} --end {end} --non-funct'
        process = subprocess.Popen([cmd], close_fds=True, shell=True)
        process.wait()
        time.sleep(2.5)
        
        #create 95% credible set files
        finemapped = pd.read_csv(f"{base}/loci/locus_{locname}.susie", sep="\t")
        finemapped = finemapped.sort_values("PIP", ascending=True)
        finemapped['cumsum'] = finemapped['PIP'].cumsum()
        finemapped = finemapped[finemapped['cumsum'] > 0.05]
        finemapped['SNP'] = finemapped.apply(lambda row: f"{row['CHR']}:{row['BP']}:{row['A1']}:{row['A2']}", axis=1)
        finemapped = finemapped[['SNP', 'PIP']]
        finemapped = finemapped.sort_values("PIP", ascending=False)
        finemapped.to_csv(f"{base}/locus_{locname}.susie.finemapped", sep="\t", index=False)

    except:
        #error if fails
        print(f"Error in {base}/{locname}")
        print(f'python ~/code/polyfun/munge_polyfun_sumstats.py --sumstats {base}/loci/locus_{locname}.txt --keep-hla --out {base}/loci/locus_{locname}.txt.pq')
    
    #remove intermediate files
    cmd = f'rm {base}/loci/locus_{locname}*'
    process = subprocess.Popen([cmd], close_fds=True, shell=True)
    process.wait()

